name: docker
services:
  autoshield-api:
    build:
      context: /Users/alishar/Desktop/autoshield/infrastructure/docker/api
      dockerfile: Dockerfile
    container_name: autoshield-api
    depends_on:
      postgres:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    environment:
      POSTGRES_DB: autoshield
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: autoshield_dev_password
      POSTGRES_USER: autoshield
      REDIS_HOST: redis
    networks:
      autoshield_net: null
  juice-shop:
    container_name: autoshield-juice-shop
    image: bkimminich/juice-shop:v19.0.0
    networks:
      autoshield_net: null
  linux-admin:
    build:
      context: /Users/alishar/Desktop/autoshield/infrastructure/docker/linux-admin
      dockerfile: Dockerfile
    container_name: autoshield-linux-admin
    networks:
      autoshield_net: null
  nginx:
    container_name: autoshield-nginx
    depends_on:
      juice-shop:
        condition: service_started
        required: true
    image: nginx:1.27-alpine
    networks:
      autoshield_net: null
    ports:
      - mode: ingress
        target: 80
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /Users/alishar/Desktop/autoshield/infrastructure/docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        bind: {}
      - type: volume
        source: nginx_logs
        target: /var/log/nginx
        volume: {}
  postgres:
    container_name: autoshield-postgres
    environment:
      POSTGRES_DB: autoshield
      POSTGRES_PASSWORD: autoshield_dev_password
      POSTGRES_USER: autoshield
    image: postgres:16-alpine
    networks:
      autoshield_net: null
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
  redis:
    command:
      - redis-server
      - --appendonly
      - 'yes'
    container_name: autoshield-redis
    image: redis:7-alpine
    networks:
      autoshield_net: null
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume: {}
networks:
  autoshield_net:
    name: autoshield_net
    driver: bridge
volumes:
  nginx_logs:
    name: docker_nginx_logs
  postgres_data:
    name: docker_postgres_data
  redis_data:
    name: docker_redis_data
